excerpt_separator: ""
pygments: true
markdown: kramdown
title: Xcopy Team
tagline: 
description: Xcopy is Billing Subscription Saas Model that allows any Mobile app to run as saas. We also support Web app and Software desktop
paginate: 5